### ISSUE TITLE
add headers bug

### ISSUE THREAD

**Issue by 501956430** [natjs/weex-nat-transfer#1]
<img width="972" alt="2017-08-09 00 06 13" src="https://user-images.githubusercontent.com/20204491/29082063-02595c8c-7c97-11e7-9db5-382c5d99af2a.png">

`//headerValues 对象是新创建的 !=null`
`if (headerValues == null) { }//条件不成立`

`for (int i = 1; i < headerValues.size(); ++i) {  
  connection.addRequestProperty();//不会执行添加header参数
}//headerValues.size == 0 条件不成立`

**Comment by 501956430** [comment]
`headerValues.getString(0);//数组下标越界`
`headers: {
        'x-app': 'nat/0.0.8',
        'x-sign': 'bfbbf4c1f087d972'
    },`

doc上 headers key:value格式，然而并未取entry.getValue

**Comment by fumpierrez** [comment]
Is there any solution? I think this is related or just the same problem I'm getting with custom headers being ignored https://github.com/natjs/weex-nat-transfer/issues/4

**Comment by 501956430** [comment]
@fumpierrez Remove the corresponding head or modify this source

**Comment by 501956430** [comment]
@fumpierrez  This plug-in has not been updated for a long time, the proposed bug has not been replied and repaired

**Comment by fumpierrez** [comment]
@501956430 Is this project unmaintained? Do you know of any alternative for weex?

**Comment by acathur** [comment]
Sorry I didn't notice this issue, it will be fixed tomorrow

**Comment by acathur** [comment]
bug fixed. install newest `nat-transfer` `0.1.6`
