### ISSUE TITLE
Nat.upload not adding custom headers on Android

### ISSUE THREAD

**Issue by fumpierrez** [natjs/weex-nat-transfer#4]
I'm trying to add a JWT for authorisation purposes but it's being ignored on Android, can't test this on IOS. Code is as follows, I'm also attaching the output of an echo server 

		apiUpload(){
			if (!this.filePath) {
				Nat.toast('Please pick a file first :)')
				return
			}

			Nat.upload(this.url, {
				path: this.filePath,
				method: 'POST',
				formData: {
					framework: 'natjs',
				},
				headers: {
					'x-sign': 'customheader',
					'x-header': 'customheader',
					'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.SomeTokenValue',
				}
			}, {
				onProgress: (p) => {
					Nat.toast('Progressing: ' + p)
				}
			}, (err, res) => {
				if (err) {
					Nat.toast('[ERROR] ' + JSON.stringify(err))
					return
				}

				Nat.toast(JSON.stringify(res))
			})
		}

With something like this, the file is posted, the formData is posted but headers are not adding the custom ones, jut just add a series of apparently default headers such as User-Agent etc but not the custom ones in my code sample. See the output of a debug server:

[server] event: connection
[connection] event: data
--> POST / HTTP/1.1
--> Content-Type: multipart/form-data; boundary=3462-1016-3362-6531551161-5167-76-98-93
--> Transfer-Encoding: chunked
--> User-Agent: Dalvik/2.1.0 (Linux; U; Android 6.0; Android SDK built for x86 Build/MASTER)
--> Host: 10.0.2.2:7777
--> Connection: Keep-Alive
--> Accept-Encoding: gzip
-->
--> 4000
--> --3462-1016-3362-6531551161-5167-76-98-93
--> Content-Disposition: form-data; name="framework"
-->
--> natjs
--> --3462-1016-3362-6531551161-5167-76-98-93
--> Content-Disposition: form-data; name="file"; filename="IMG_20171231_185954.jpg"
--> Content-Type: image/jpeg
-->
--> ����JFIF��9dExifIIbj(2 REST OF BINARY DATA

**Comment by acathur** [comment]
duplicate with #1
